### PR TITLE
H1 and BugCrowd updates

### PR DESCRIPTION
**Pull request by 0xn3va**
This PR contains the following changes:

1. New GitHub orgs have been added for H1 and BugCrowd programs.
2. Dead programs have been removed from the lists.
3. GitHub orgs have been removed from programs they do not own.

I'd like to add that I've read your contribution guide at https://github.com/nikitastupin/orgs-data/blob/main/CONTRIBUTING.md but it looks too complicated to contribute changes :) So, I tried to contribute in this way, if you do not like it, feel free to decline this PR, I'm completely OK with that. Thanks!

### CODE REVIEW

**Comment by nikitastupin** [comment]
Hey @0xn3va,

Thanks! I'm going to take a look later this week 👀 

And also thanks for your feedback on the contribution guidelines. I'll try to simplify them (and the process too). If you have any ideas on that feel free to share!

Thank you again!

**Comment by 0xn3va** [comment]
Hey @nikitastupin,

The contribution guide itself is easy to use, but proposing multiple changes through Google forms is inconvenient. From my point of view, it would be possible to add an option through opening a PR and offer a general approach to opening it, for example, an author should follow the defined notation and pre-process final tables before opening a PR (sort them, replace spaces with tabs, and etc.). If this path is acceptable, it would be awesome to have such option in the future.

Thanks!

**Comment by nikitastupin** [comment]
Hey @0xn3va! These contributions are amazing, thanks! I can't believe I've missed so many orgs 😄

I've decided to keep some of the dead programs because these programs have most likely migrated somewhere else. So if there would be an issue, I think we can just find another channel to reach out to them. Does this make sense to you?

**Comment by nikitastupin** [comment]
I've moved your feedback on the contribution guidelines to #10 to ponder on that later. Thanks again!

**Comment by 0xn3va** [comment]
Hey @nikitastupin! Thanks for looking at this! 

> I've decided to keep some of the dead programs because these programs have most likely migrated somewhere else

Yeah, it makes sense, I like the approach

> I've moved your feedback on the contribution guidelines to https://github.com/nikitastupin/orgs-data/issues/10 to ponder on that later

Fab, feel free to ping me if you need more details or I can help in some way

Cheers!

**Pull request merged**
